background {
    monitor =
    path = ~/.config/.current_wallpaper
    blur_passes = 2
    noise = 0.2
}

general {
    hide_cursor = true
}

label {
    monitor =
    text = $USER
    color = rgba(216, 222, 233, 0.80)
    font_size = 25
    font_family = FiraCode Nerd Font
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 450, 90

    dots_text_format = *

    fail_text = ERROR 404: Brain Not Found (¬_¬")

    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = FiraCode Nerd Font
    placeholder_text = 
    hide_input = false
    halign = center
    valign = center
}

label {
    monitor =
    text = -> $LAYOUT <-
    color = rgba(216, 222, 233, 0.80)
    font_size = 20
    font_family = FiraCode Nerd Font
    position = 0, -100
    halign = center
    valign = center
}
